<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Masuk | DIBA Console</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    <style>
        :root{--ink:#152528;--muted:#718083;--teal:#087f75;--lime:#c7ee73;--line:#dce8e4}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#edf5f1;color:var(--ink);font-family:'DM Sans',sans-serif}.login{width:min(930px,calc(100% - 30px));min-height:570px;display:grid;grid-template-columns:43% 57%;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 20px 60px #173d3620}.intro{padding:52px 44px;background:#103b38;color:#e8f4df;position:relative;overflow:hidden}.intro:after{content:'';position:absolute;width:220px;height:220px;border:38px solid #c7ee7330;border-radius:50%;right:-85px;bottom:-75px}.mark{display:inline-grid;place-items:center;width:40px;height:40px;border-radius:12px 12px 4px 12px;background:var(--lime);color:var(--ink);font:700 22px 'Space Grotesk'}.intro h1{font:700 46px 'Space Grotesk';margin:75px 0 14px;letter-spacing:-1px}.intro p{max-width:270px;line-height:1.7;color:#b9d4c8;font-size:15px}.intro-note{position:absolute;bottom:42px;color:#8eafa4;font-size:12px}.form{padding:58px 64px;display:flex;flex-direction:column;justify-content:center}.eyebrow{color:var(--teal);font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase}.form h2{font:700 32px 'Space Grotesk';margin:9px 0}.subtitle{color:var(--muted);margin:0 0 30px}.field{margin-bottom:19px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:8px}.field input{width:100%;padding:13px;border:1px solid var(--line);border-radius:8px;font:14px 'DM Sans';outline:0}.field input:focus{border-color:var(--teal);box-shadow:0 0 0 3px #dff2ee}.remember{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin:4px 0 24px}.remember input{accent-color:var(--teal)}button{width:100%;padding:14px;border:0;border-radius:8px;background:var(--teal);color:#fff;font:700 14px 'DM Sans';cursor:pointer}button:hover{background:#06675f}.error{background:#fce9e7;color:#9d4038;padding:12px;border-radius:8px;margin-bottom:18px;font-size:13px}@media(max-width:650px){.login{display:block}.intro{padding:30px;height:210px}.intro h1{margin:25px 0 5px;font-size:34px}.intro p{margin:0}.intro-note{display:none}.form{padding:35px 28px}}
            :root{--ink:#152528;--muted:#718083;--teal:#119db4;--lime:#c7ee73;--line:#dce8e4}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f1f3f6;color:var(--ink);font-family:'DM Sans',sans-serif}.login{width:min(930px,calc(100% - 30px));min-height:570px;display:grid;grid-template-columns:43% 57%;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 20px 60px #173d3620}.intro{padding:52px 44px;background:#343a40;color:#e8f4df;position:relative;overflow:hidden}.intro:after{content:'';position:absolute;width:220px;height:220px;border:38px solid #e9ecef30;border-radius:50%;right:-85px;bottom:-75px}.mark{display:inline-grid;place-items:center;width:40px;height:40px;border-radius:12px 12px 4px 12px;background:#e9ecef;color:#59636b;font:700 22px 'Space Grotesk'}.intro h1{font:700 46px 'Space Grotesk';margin:75px 0 14px;letter-spacing:-1px}.intro p{max-width:270px;line-height:1.7;color:#b9d4c8;font-size:15px}.intro-note{position:absolute;bottom:42px;color:#8eafa4;font-size:12px}.form{padding:58px 64px;display:flex;flex-direction:column;justify-content:center}.eyebrow{color:var(--teal);font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase}.form h2{font:700 32px 'Space Grotesk';margin:9px 0}.subtitle{color:var(--muted);margin:0 0 30px}.field{margin-bottom:19px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:8px}.field input{width:100%;padding:13px;border:1px solid var(--line);border-radius:8px;font:14px 'DM Sans';outline:0}.field input:focus{border-color:var(--teal);box-shadow:0 0 0 3px #dff2ee}.remember{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin:4px 0 24px}.remember input{accent-color:var(--teal)}button{width:100%;padding:14px;border:0;border-radius:8px;background:var(--teal);color:#fff;font:700 14px 'DM Sans';cursor:pointer}button:hover{background:#06675f}.error{background:#fce9e7;color:#9d4038;padding:12px;border-radius:8px;margin-bottom:18px;font-size:13px}@media(max-width:650px){.login{display:block}.intro{padding:30px;height:210px}.intro h1{margin:25px 0 5px;font-size:34px}.intro p{margin:0}.intro-note{display:none}.form{padding:35px 28px}}
    </style>
</head>
<body><div class="login"><section class="intro"><span class="mark">D</span><h1>DIBA</h1><p>Kelola inventaris aplikasi digital dalam satu ruang kerja yang ringkas dan teratur.</p><div class="intro-note">Digital Inventory &amp; Business Applications</div></section><section class="form"><div class="eyebrow">Admin workspace</div><h2>Selamat datang kembali</h2><p class="subtitle">Masuk untuk mengelola katalog aplikasi.</p>@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('login.process') }}">@csrf<div class="field"><label for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email') }}" placeholder="nama@instansi.go.id" required autofocus></div><div class="field"><label for="password">Password</label><input id="password" type="password" name="password" placeholder="Masukkan password" required></div><label class="remember"><input type="checkbox" name="remember"> Ingat saya di perangkat ini</label><button type="submit">Masuk ke dashboard</button></form></section></div></body>
</html>
