@extends('layouts.app')
@section('content')
@include('security._styles')
<div class="security-page">
    <header class="sec-head"><div><div class="sec-crumb"><a href="{{ route('security.dashboard') }}">Beranda</a>　›　<a href="{{ route('security.findings.index') }}">Keamanan Aplikasi</a>　›　Temuan　›　Detail</div><h1 class="page-title">Detail Temuan Keamanan</h1><p class="sec-subtitle">Informasi lengkap temuan, bukti, dan tindak lanjut penanganan.</p></div><div class="sec-actions"><a class="sec-button light" href="{{ route('security.findings.index') }}"><i class="bi bi-arrow-left"></i> Kembali</a><a class="sec-button" href="{{ route('security.findings.memo', $finding) }}"><i class="bi bi-file-earmark-pdf"></i> Unduh Nota Dinas</a></div></header>
    @if(session('success'))<div class="sec-alert"><i class="bi bi-check-circle-fill"></i> {{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert errors"><ul style="margin:0;padding-left:18px">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="sec-detail-banner"><div style="display:flex;align-items:center;gap:14px"><i class="bi bi-shield-fill-exclamation" style="font-size:31px"></i><div><h2>{{ $finding->title }}</h2><div>{{ $finding->reference_code }}　|　Tanggal: {{ $finding->found_at?->translatedFormat('d F Y H:i') }}</div></div><span class="sec-badge {{ strtolower($finding->severity) }}">{{ $finding->severity }}</span></div><span class="sec-badge status-{{ $finding->status === 'Baru' ? 'baru' : ($finding->status === 'Dalam Penanganan' ? 'dalam' : ($finding->status === 'Menunggu Verifikasi' ? 'menunggu' : 'selesai')) }}">{{ $finding->status }}</span></section>
    <nav class="sec-tabs"><a class="active" href="#informasi"><i class="bi bi-file-text"></i> Informasi</a><a href="#rekomendasi"><i class="bi bi-lightbulb"></i> Rekomendasi</a><a href="#tindak-lanjut"><i class="bi bi-arrow-repeat"></i> Tindak Lanjut</a><a href="#bukti"><i class="bi bi-image"></i> Bukti ({{ $finding->evidence->count() }})</a><a href="#riwayat"><i class="bi bi-clock-history"></i> Riwayat</a><a href="#nota-dinas"><i class="bi bi-envelope-paper"></i> Surat/Nota Dinas</a></nav>
    <div class="sec-detail-grid" style="margin-top:14px">
        <main>
            <section class="sec-card" id="informasi"><div class="sec-card-head"><span><i class="bi bi-shield-lock-fill"></i> Informasi Temuan</span></div><div class="sec-card-body"><div class="sec-info-grid">
                <div class="sec-info-row"><strong>Aplikasi</strong><span>{{ $finding->application_name }}</span></div><div class="sec-info-row"><strong>Jenis Temuan</strong><span>{{ $finding->finding_type }}</span></div>
                <div class="sec-info-row"><strong>URL</strong><span>@if($finding->application_url)<a href="{{ $finding->application_url }}" target="_blank" rel="noopener">{{ $finding->application_url }} <i class="bi bi-box-arrow-up-right"></i></a>@else—@endif</span></div><div class="sec-info-row"><strong>Severity</strong><span><span class="sec-badge {{ strtolower($finding->severity) }}">{{ $finding->severity }}</span></span></div>
                <div class="sec-info-row"><strong>Perangkat Daerah</strong><span>{{ $finding->owner }}</span></div><div class="sec-info-row"><strong>Sumber</strong><span>{{ $finding->source }}</span></div>
                <div class="sec-info-row"><strong>Kategori</strong><span>{{ $finding->category }}</span></div><div class="sec-info-row"><strong>PIC SOC</strong><span>{{ $finding->reporter?->name ?? 'Administrator' }}</span></div>
                <div class="sec-info-row"><strong>Tanggal Temuan</strong><span>{{ $finding->found_at?->translatedFormat('d F Y H:i') }} WIB</span></div><div class="sec-info-row"><strong>Status</strong><span><span class="sec-badge status-{{ $finding->status === 'Baru' ? 'baru' : ($finding->status === 'Dalam Penanganan' ? 'dalam' : ($finding->status === 'Menunggu Verifikasi' ? 'menunggu' : 'selesai')) }}">{{ $finding->status }}</span></span></div>
                <div class="sec-info-row"><strong>Batas Tindak Lanjut</strong><span>{{ $finding->deadline?->translatedFormat('d F Y') ?? 'Belum ditentukan' }} @if($finding->deadline && $finding->status !== 'Selesai')<span class="sec-count">({{ $finding->deadline->isPast() ? 'Terlambat' : $finding->deadline->diffForHumans() }})</span>@endif</span></div><div class="sec-info-row"><strong>Terakhir diperbarui</strong><span>{{ $finding->updated_at->translatedFormat('d F Y H:i') }}</span></div>
            </div><div class="sec-text-block"><h3><i class="bi bi-file-text"></i> Deskripsi Temuan</h3><p>{{ $finding->description }}</p></div>@if($finding->impact)<div class="sec-text-block"><h3><i class="bi bi-exclamation-triangle-fill" style="color:#df394a"></i> Dampak</h3><p>{{ $finding->impact }}</p></div>@endif</div></section>
            <section class="sec-card" id="rekomendasi" style="margin-top:14px"><div class="sec-card-head"><span><i class="bi bi-lightbulb-fill"></i> Rekomendasi Penanganan</span></div><div class="sec-card-body"><div class="sec-text-block"><p>{{ $finding->recommendation ?: 'Belum ada rekomendasi yang dicatat.' }}</p></div></div></section>
            <section class="sec-card" id="tindak-lanjut" style="margin-top:14px"><div class="sec-card-head"><span><i class="bi bi-arrow-repeat"></i> Tindak Lanjut</span></div><div class="sec-card-body">
                @if($finding->follow_up)<div class="sec-callout" style="margin-bottom:14px"><strong>Tindak lanjut terakhir</strong><p style="white-space:pre-line;margin:5px 0 0">{{ $finding->follow_up }}</p></div>@endif
                <form method="POST" action="{{ route('security.findings.follow-up', $finding) }}" enctype="multipart/form-data" class="sec-form">@csrf
                    <div class="sec-callout" style="margin-bottom:13px"><i class="bi bi-info-circle-fill"></i> Catat langkah perbaikan dan unggah bukti penyelesaian untuk ditinjau.</div>
                    <label for="follow_up">Catatan Tindak Lanjut <span class="sec-required">*</span></label><textarea id="follow_up" name="follow_up" required maxlength="10000" placeholder="Jelaskan perbaikan yang telah dilakukan...">{{ old('follow_up') }}</textarea>
                    <div class="sec-form-grid" style="margin-top:12px"><div><label for="follow-up-status">Status setelah tindak lanjut <span class="sec-required">*</span></label><select id="follow-up-status" name="status" required>@foreach(['Dalam Penanganan', 'Menunggu Verifikasi', 'Selesai'] as $status)<option value="{{ $status }}" @selected(old('status', 'Dalam Penanganan') === $status)>{{ $status }}</option>@endforeach</select></div><div><label for="follow-up-evidence">Bukti Perbaikan (opsional)</label><input id="follow-up-evidence" type="file" name="evidence[]" accept=".jpg,.jpeg,.png,.pdf,.zip,.txt,.log" multiple></div></div>
                    <div class="sec-actions" style="margin-top:14px"><button class="sec-button" type="submit"><i class="bi bi-send-fill"></i> Kirim Tindak Lanjut</button></div>
                </form>
                @if($finding->pic_name || $finding->pic_email)<div class="sec-text-block" style="margin-top:15px"><h3>PIC Perangkat Daerah</h3><p>{{ $finding->pic_name ?: 'Belum ditentukan' }} @if($finding->pic_email) · <a href="mailto:{{ $finding->pic_email }}">{{ $finding->pic_email }}</a>@endif</p></div>@endif
            </div></section>
        </main>
        <aside>
            <section class="sec-card" id="bukti"><div class="sec-card-head"><span><i class="bi bi-image"></i> Screenshot / Bukti Temuan</span></div><div class="sec-card-body">@if($finding->evidence->isNotEmpty())<div class="sec-evidence-list">@foreach($finding->evidence as $evidence)<div class="sec-evidence-item"><span><i class="bi bi-file-earmark"></i> {{ $evidence->original_name }}<br><small>{{ number_format($evidence->size / 1024, 0) }} KB · {{ $evidence->created_at->format('d M Y') }}</small></span><a class="sec-button small light" href="{{ route('security.findings.evidence', [$finding, $evidence]) }}"><i class="bi bi-download"></i> Unduh</a></div>@endforeach</div>@else<div class="sec-empty">Belum ada bukti yang diunggah.</div>@endif</div></section>
            <section class="sec-card" id="riwayat" style="margin-top:14px"><div class="sec-card-head"><span><i class="bi bi-clock-history"></i> Riwayat Aktivitas</span></div><div class="sec-card-body"><div class="sec-timeline">@forelse($finding->activities as $activity)<div class="sec-timeline-item"><strong>{{ $activity->event }}</strong>@if($activity->from_status || $activity->to_status)<p>{{ $activity->from_status ?: '—' }} <i class="bi bi-arrow-right"></i> {{ $activity->to_status }}</p>@endif @if($activity->note)<p>{{ $activity->note }}</p>@endif<p>{{ $activity->user?->name ?? 'Pengguna' }}</p><time>{{ $activity->created_at->translatedFormat('d M Y H:i') }}</time></div>@empty<div class="sec-empty">Belum ada riwayat.</div>@endforelse</div></div></section>
            <section class="sec-card" id="nota-dinas" style="margin-top:14px"><div class="sec-card-head"><span><i class="bi bi-envelope-paper"></i> Surat / Nota Dinas</span></div><div class="sec-card-body"><p class="sec-subtitle" style="margin:0 0 12px">Unduh ringkasan temuan ini sebagai nota dinas PDF.</p><a class="sec-button" style="width:100%" href="{{ route('security.findings.memo', $finding) }}"><i class="bi bi-file-earmark-pdf"></i> Unduh Nota Dinas</a><form method="POST" action="{{ route('security.findings.status', $finding) }}" style="margin-top:18px" class="sec-form">@csrf @method('PATCH')<label for="status-update">Perbarui Status</label><select id="status-update" name="status">@foreach($statuses as $status)<option value="{{ $status }}" @selected($finding->status === $status)>{{ $status }}</option>@endforeach</select><input name="note" style="margin-top:8px" placeholder="Catatan perubahan status (opsional)"><button class="sec-button light" style="width:100%;margin-top:8px" type="submit">Simpan Status</button></form></div></section>
            @if($finding->internal_note)<section class="sec-card" style="margin-top:14px"><div class="sec-card-head"><span><i class="bi bi-sticky"></i> Catatan Internal</span></div><div class="sec-card-body"><p style="white-space:pre-line;margin:0">{{ $finding->internal_note }}</p></div></section>@endif
        </aside>
    </div>
</div>
@endsection
