@extends('layouts.app')
@section('content')
<div class="topbar"><div><div class="eyebrow">Workspace / katalog</div><h1 class="page-title">Daftar aplikasi</h1></div><a class="button" href="{{ route('applications.create') }}">+ Tambah aplikasi</a></div>
@if(session('success')) <div class="alert">{{ session('success') }}</div> @endif
<div class="panel"><div class="panel-head"><div><h2>Daftar Aplikasi</h2></div></div><form class="filter-bar" method="GET"><select name="owner" aria-label="Filter owner"><option value="">Semua Owner</option>@foreach($owners as $owner)<option value="{{ $owner }}" {{ request('owner') === $owner ? 'selected' : '' }}>{{ $owner }}</option>@endforeach</select><button class="button" type="submit"><i class="bi bi-search"></i> Filter</button></form>
<div class="table-tools"><div class="table-tools-left">Tampilkan <select aria-label="Jumlah entri"><option>10</option><option>25</option><option>50</option></select> entri <button class="tool-button copy" type="button"><i class="bi bi-copy"></i> Salin</button><button class="tool-button pdf" type="button"><i class="bi bi-file-earmark-pdf"></i> PDF</button><button class="tool-button print" type="button" onclick="window.print()"><i class="bi bi-printer"></i> Cetak</button><button class="tool-button columns" type="button"><i class="bi bi-eye"></i> Kolom</button></div><label class="table-tools-right">Cari: <input id="tableSearch" type="search" placeholder="Cari tabel..."></label></div>
<div class="table-wrap"><table id="applicationsTable"><thead><tr><th>No</th><th>Nama Aplikasi</th><th>Kode</th><th>URL</th><th>Deskripsi</th><th>Pemilik Aplikasi</th><th>Aksi</th></tr></thead><tbody>
@forelse($applications as $application)<tr><td>{{ $applications->firstItem() + $loop->index }}</td><td><div class="app-name">{{ $application->name }}</div></td><td>{{ $application->code }}</td><td>@if($application->url)<a style="color:#087cf0" href="{{ $application->url }}" target="_blank">{{ parse_url($application->url, PHP_URL_HOST) ?: $application->url }}</a>@else - @endif</td><td class="muted">{{ \Illuminate\Support\Str::limit($application->description ?: '-', 90) }}</td><td>{{ $application->owner ?: '-' }}</td><td><div class="actions"><a class="icon-button" href="{{ route('applications.show', $application) }}"><i class="bi bi-info-circle-fill"></i> Detail</a><a class="icon-button" href="{{ route('applications.pdf', $application) }}"><i class="bi bi-file-earmark-pdf-fill"></i> PDF</a><a class="icon-button" href="{{ route('applications.edit', $application) }}"><i class="bi bi-pencil-fill"></i> Edit</a><form method="POST" action="{{ route('applications.destroy', $application) }}" onsubmit="return confirm('Hapus aplikasi ini?')">@csrf @method('DELETE')<button class="icon-button delete" type="submit"><i class="bi bi-trash-fill"></i> Hapus</button></form></div></td></tr>@empty<tr><td colspan="7" class="muted">Data belum tersedia.</td></tr>@endforelse
</tbody></table></div><div class="pagination-bar"><div>Menampilkan {{ $applications->firstItem() ?: 0 }} sampai {{ $applications->lastItem() ?: 0 }} dari {{ $applications->total() }} entri</div><div class="pagination"><a class="{{ $applications->onFirstPage() ? 'disabled' : '' }}" href="{{ $applications->previousPageUrl() ?: '#' }}">Sebelumnya</a>@foreach($applications->getUrlRange(max(1, $applications->currentPage() - 2), min($applications->lastPage(), $applications->currentPage() + 2)) as $page => $url)<a class="{{ $page == $applications->currentPage() ? 'current' : '' }}" href="{{ $url }}">{{ $page }}</a>@endforeach<a class="{{ $applications->currentPage() == $applications->lastPage() ? 'disabled' : '' }}" href="{{ $applications->nextPageUrl() ?: '#' }}">Selanjutnya</a></div></div></div>
<footer class="site-footer">&copy; {{ date('Y') }} DIBA Katalog Aplikasi Jawa Barat</footer>
@endsection
