@extends('layouts.app')
@section('content')
<div class="topbar"><div><div class="eyebrow">Workspace / katalog</div><h1 class="page-title">Daftar aplikasi</h1></div><a class="button" href="{{ route('applications.create') }}">+ Tambah aplikasi</a></div>
@if(session('success')) <div class="alert">{{ session('success') }}</div> @endif
<div class="panel"><div class="panel-head"><div><h2>Inventaris digital</h2><div class="muted" style="font-size:13px;margin-top:5px">Kelola aplikasi dan informasi teknologinya.</div></div><form class="search" method="GET"><select name="owner" aria-label="Filter owner"><option value="">Semua Owner</option>@foreach($owners as $owner)<option value="{{ $owner }}" {{ request('owner') === $owner ? 'selected' : '' }}>{{ $owner }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" placeholder="Cari nama atau kode..."><button class="button secondary" type="submit">Filter</button></form></div>
<div class="table-wrap"><table><thead><tr><th>Aplikasi</th><th>Pemilik / layanan</th><th>Teknologi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($applications as $application)<tr><td><div class="code">{{ $application->code }}</div><div class="app-name">{{ $application->name }}</div><div class="muted">{{ $application->year ?: 'Tahun belum diisi' }}</div></td><td>{{ $application->owner ?: '-' }}<div class="muted">{{ $application->service ?: '-' }}</div></td><td>{{ $application->language ?: '-' }}<div class="muted">{{ $application->database ?: '-' }}</div></td><td><span class="status {{ strtolower(str_replace(' ', '-', $application->status)) }}">{{ $application->status }}</span></td><td><div class="actions"><a class="icon-button" href="{{ route('applications.edit', $application) }}">Edit</a><form method="POST" action="{{ route('applications.destroy', $application) }}" onsubmit="return confirm('Hapus aplikasi ini?')">@csrf @method('DELETE')<button class="icon-button delete" type="submit">Hapus</button></form></div></td></tr>@empty<tr><td colspan="5" class="muted">Data belum tersedia.</td></tr>@endforelse
</tbody></table></div><div class="pagination-bar"><div>Menampilkan {{ $applications->firstItem() ?: 0 }} sampai {{ $applications->lastItem() ?: 0 }} dari {{ $applications->total() }} entri</div><div class="pagination"><a class="{{ $applications->onFirstPage() ? 'disabled' : '' }}" href="{{ $applications->previousPageUrl() ?: '#' }}">Sebelumnya</a>@foreach($applications->getUrlRange(max(1, $applications->currentPage() - 2), min($applications->lastPage(), $applications->currentPage() + 2)) as $page => $url)<a class="{{ $page == $applications->currentPage() ? 'current' : '' }}" href="{{ $url }}">{{ $page }}</a>@endforeach<a class="{{ $applications->currentPage() == $applications->lastPage() ? 'disabled' : '' }}" href="{{ $applications->nextPageUrl() ?: '#' }}">Selanjutnya</a></div></div></div>
<footer class="site-footer">&copy; {{ date('Y') }} DIBA Katalog Aplikasi Jawa Barat</footer>
@endsection
