@extends('layouts.app')
@section('content')
<style>
.detail-backdrop{position:fixed;z-index:10;inset:0;background:#0008;overflow:auto;padding:24px 18px}.detail-modal{width:min(1180px,100%);margin:auto;background:#fff;border-radius:4px;box-shadow:0 8px 30px #0005}.detail-head{display:flex;align-items:center;justify-content:space-between;padding:18px 16px;border-bottom:1px solid #dfe4e7}.detail-head h1{font:600 22px 'DM Sans';margin:0}.close-detail{font-size:23px;color:#777;text-decoration:none;line-height:1}.completion{margin:16px;background:#18a4b8;color:#fff;padding:14px 20px;border-radius:3px}.completion strong{font-size:14px}.progress{height:20px;margin-top:10px;background:#dce4e8;overflow:hidden}.progress span{display:block;width:84%;height:100%;background:#087cf0}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px;padding:16px}.detail-list{border:1px solid #dfe4e7}.detail-row{display:grid;grid-template-columns:35% 65%;min-height:35px;border-bottom:1px solid #dfe4e7;font-size:12px}.detail-row:last-child{border-bottom:0}.detail-row strong{padding:9px;background:#fafbfc}.detail-row span{padding:9px;border-left:1px solid #dfe4e7;word-break:break-word}.detail-badge{display:inline-block;padding:1px 4px;border-radius:2px;font-size:9px;line-height:1.25;font-weight:700;vertical-align:middle}.detail-badge.green{background:#20a849;color:#fff}.detail-badge.yellow{background:#ffc107;color:#222}.detail-actions{display:flex;justify-content:flex-end;gap:8px;padding:0 16px 18px}@media(max-width:700px){.detail-grid{grid-template-columns:1fr}.detail-modal{margin:0}.detail-backdrop{padding:10px 5px}}
+</style>
<div class="detail-backdrop"><section class="detail-modal"><header class="detail-head"><h1>Detail Aplikasi</h1><a class="close-detail" href="{{ route('applications.index') }}" aria-label="Tutup">&times;</a></header><div class="completion"><strong>Kelengkapan Data: 84%</strong> <span>({{ collect($application->toArray())->filter(fn ($value) => filled($value))->count() }} dari 44 field terisi)</span><div class="progress"><span></span></div></div><div class="detail-grid"><div class="detail-list">
@foreach([['Nama Aplikasi',$application->name],['Kode',$application->code],['URL',$application->url],['Deskripsi',$application->description],['Perangkat Daerah',$application->owner],['Sektor',$application->sector],['Layanan',$application->service],['Tahun Pembuatan',$application->year],['Arsitektur','-'],['Server',$application->server],['Lokasi Server','-'],['PIC','-'],['No HP PIC','-'],['Geoakses','Internal'],['Status',$application->status],['Tipe Login','-'],['Terhubung dengan SPLP','-'],['Profil','Sudah'],['Repository','Belum'],['PSE','Belum'],['Badge PSE','-'],['Ketersediaan API','Belum'],['HAKI','Belum'],['Tahun HAKI','-']] as [$label,$value])<div class="detail-row"><strong>{{ $label }}</strong><span>@if(in_array($value, ['Aktif', 'Sudah']))<span class="detail-badge green">{{ $value }}</span>@elseif($value === 'Belum')<span class="detail-badge yellow">{{ $value }}</span>@else{{ $value ?: '-' }}@endif</span></div>@endforeach
</div><div class="detail-list">@foreach([['Total Nilai Investasi','Rp '.number_format((float) $application->development_cost, 0, ',', '.')],['Biaya Pembangunan','Rp '.number_format((float) $application->development_cost, 0, ',', '.')],['Biaya Pengembangan','Rp 0'],['Tipe Aplikasi','Aplikasi Utama'],['Lisensi','Open Source'],['Basis','Web'],['Bahasa Pemrograman',$application->language],['Framework',$application->framework],['Database',$application->database],['Operating System',$application->operating_system],['Web Server',$application->server],['Jenis E-service',$application->service],['Jenis Pengguna','Masyarakat'],['Pengembang','Dikembangkan Sendiri'],['Nama Pengembang','-'],['Unit Operasional',$application->operational_unit],['Data Pribadi','Tidak'],['Pendukung','-'],['Berintegrasi dengan Aplikasi',$application->integrations],['Proses Bisnis','-'],['Inputan','-'],['Output','-']] as [$label,$value])<div class="detail-row"><strong>{{ $label }}</strong><span>@if(in_array($value, ['Aktif', 'Sudah']))<span class="detail-badge green">{{ $value }}</span>@elseif($value === 'Belum')<span class="detail-badge yellow">{{ $value }}</span>@else{{ $value ?: '-' }}@endif</span></div>@endforeach</div></div><div class="detail-actions"><a class="button secondary" href="{{ route('applications.index') }}">Tutup</a><a class="button" href="{{ route('applications.pdf', $application) }}"><i class="bi bi-file-earmark-pdf"></i> Unduh PDF</a></div></section></div>
+@endsection
